# Generated by Django 3.1.3 on 2021-08-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApi', '0002_auto_20210804_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
